module.exports = {
  apps: [
    {
      name: "crictrade-backend",
      cwd: "/root/crichd/crictrade/backend",
      script: "dist/index.js",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        DATABASE_URL: "postgresql://crictrade:crictrade_dev@localhost:5432/crictrade",
        RPC_URL: "https://testnet-rpc.wirefluid.com",
        CRICKET_API_KEY: "",
        FACTORY_ADDRESS: "",
        ORACLE_PRIVATE_KEY: "",
      },
      watch: false,
      instances: 1,
      autorestart: true,
      max_memory_restart: "500M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/root/crichd/crictrade/logs/backend-error.log",
      out_file: "/root/crichd/crictrade/logs/backend-out.log",
      merge_logs: true,
    },
    {
      name: "crictrade-frontend",
      cwd: "/root/crichd/crictrade/frontend",
      script: ".next/standalone/server.js",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        HOSTNAME: "0.0.0.0",
        NEXT_PUBLIC_API_URL: "http://149.102.129.143:3001",
        NEXT_PUBLIC_AI_API_URL: "http://149.102.129.143:5001",
      },
      watch: false,
      instances: 1,
      autorestart: true,
      max_memory_restart: "500M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/root/crichd/crictrade/logs/frontend-error.log",
      out_file: "/root/crichd/crictrade/logs/frontend-out.log",
      merge_logs: true,
    },
    {
      name: "crictrade-ai",
      cwd: "/root/crichd/crictrade/ai-engine",
      script: "server.py",
      interpreter: "python3",
      env: {
        FLASK_PORT: 5001,
        FLASK_DEBUG: "false",
        LOG_LEVEL: "INFO",
        ANTHROPIC_API_KEY: "",
        CHROMADB_PATH: "/root/crichd/crictrade/ai-engine/data/chromadb",
      },
      watch: false,
      instances: 1,
      autorestart: true,
      max_memory_restart: "1G",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/root/crichd/crictrade/logs/ai-error.log",
      out_file: "/root/crichd/crictrade/logs/ai-out.log",
      merge_logs: true,
    },
  ],
};
