module.exports = {
  apps: [
    {
      name: "overflow-backend",
      cwd: "/root/crichd/overflow/backend",
      script: "dist/index.js",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        DATABASE_URL: "postgresql://overflow:overflow_dev@localhost:5432/overflow",
        RPC_URL: "https://testnet-rpc.wirefluid.com",
        CRICKET_API_KEY: "3f8971a7-5b66-499d-b429-bfc72e35b920",
        FACTORY_ADDRESS: "",
        ORACLE_PRIVATE_KEY: "",
      },
      watch: false,
      instances: 1,
      autorestart: true,
      max_memory_restart: "500M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/root/crichd/overflow/logs/backend-error.log",
      out_file: "/root/crichd/overflow/logs/backend-out.log",
      merge_logs: true,
    },
    {
      name: "overflow-frontend",
      cwd: "/root/crichd/overflow/frontend",
      script: "node_modules/.bin/next",
      args: "dev -H 0.0.0.0 -p 3000",
      env: {
        NODE_ENV: "development",
        PORT: 3000,
        NEXT_PUBLIC_API_URL: "http://149.102.129.143:3001",
        NEXT_PUBLIC_AI_API_URL: "http://149.102.129.143:5001",
      },
      watch: false,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "500M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/root/crichd/overflow/logs/frontend-error.log",
      out_file: "/root/crichd/overflow/logs/frontend-out.log",
      merge_logs: true,
    },
    {
      name: "overflow-ai",
      cwd: "/root/crichd/overflow/ai-engine",
      script: "server.py",
      interpreter: "python3",
      env: {
        FLASK_PORT: 5001,
        FLASK_DEBUG: "false",
        LOG_LEVEL: "INFO",
        ANTHROPIC_API_KEY: "",
        CHROMADB_PATH: "/root/crichd/overflow/ai-engine/data/chromadb",
      },
      watch: false,
      instances: 1,
      autorestart: true,
      max_memory_restart: "1G",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/root/crichd/overflow/logs/ai-error.log",
      out_file: "/root/crichd/overflow/logs/ai-out.log",
      merge_logs: true,
    },
  ],
};
