module.exports = {
  apps: [
    {
      name: "overflow-backend",
      cwd: "/root/crichd/overflow/backend",
      script: "dist/index.js",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      watch: false,
      autorestart: true,
      max_memory_restart: "512M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/root/crichd/overflow/logs/backend-error.log",
      out_file: "/root/crichd/overflow/logs/backend-out.log",
      merge_logs: true,
    },
    {
      name: "overflow-frontend",
      cwd: "/root/crichd/overflow/frontend",
      script: "node_modules/.bin/next",
      args: "start -p 3000",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      watch: false,
      autorestart: true,
      max_memory_restart: "256M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/root/crichd/overflow/logs/frontend-error.log",
      out_file: "/root/crichd/overflow/logs/frontend-out.log",
      merge_logs: true,
    },
    {
      name: "overflow-ai",
      cwd: "/root/crichd/overflow/ai-engine",
      script: "server.py",
      interpreter: "python3",
      instances: 1,
      exec_mode: "fork",
      env: {
        FLASK_PORT: 5001,
        FLASK_DEBUG: "false",
        LOG_LEVEL: "INFO",
      },
      watch: false,
      autorestart: true,
      max_memory_restart: "1G",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/root/crichd/overflow/logs/ai-error.log",
      out_file: "/root/crichd/overflow/logs/ai-out.log",
      merge_logs: true,
    },
  ],
};
